use fastcdc::{v2016, v2020};

const EXPECTED: &[(usize, usize)] = &[
    (0, 100081),
    (100081, 33106),
    (133187, 69903),
    (203090, 49442),
    (252532, 103705),
    (356237, 144977),
    (501214, 214287),
    (715501, 145480),
    (860981, 50981),
    (911962, 37677),
    (949639, 79457),
    (1029096, 19480),
];

const PRESETS: &[(usize, usize, usize)] = &[
    (16 * 1024, 64 * 1024, 256 * 1024),
    (32 * 1024, 128 * 1024, 512 * 1024),
    (64 * 1024, 256 * 1024, 1024 * 1024),
];

// FNV-1a 64 digests of the ChunkShift scalar cut lists, generated by the
// independent Python reference (tools/reference/fastcdc_reference.py
// --print-fixture-digests) for (fixture, target). #99 L1.
const EXPECTED_FIXTURE_DIGESTS: &[(&str, usize, u64)] = &[
    ("xorshift-1m", 65536, 0x259bdfaf8c068fd9),
    ("xorshift-1m-minus-1", 65536, 0x27978d2329d4f2ee),
    ("zero-1m", 65536, 0xd9d0423596bbe425),
    ("pattern7-1m", 65536, 0xd9d0423596bbe425),
    ("low-entropy-1m", 65536, 0x06efcccd64876221),
    ("alternating-1m", 65536, 0x916a6a99875bf022),
    ("odd-eof-transient", 65536, 0x5746b5ee65e8c544),
    ("edge-minimum-1", 65536, 0xb03cf1b9a107f86b),
    ("edge-minimum+0", 65536, 0xdcbf024dd5f41b25),
    ("edge-minimum+1", 65536, 0xbdc43b44cb04d104),
    ("edge-target-1", 65536, 0x5b9e0f252c1341ab),
    ("edge-target+0", 65536, 0xab89bb86730d9e2c),
    ("edge-target+1", 65536, 0x45bbbce34401e07d),
    ("edge-maximum-1", 65536, 0x060282e0655707de),
    ("edge-maximum+0", 65536, 0xb21353787c45bca7),
    ("edge-maximum+1", 65536, 0xda0f4034bef199f4),
    ("xorshift-1m", 131072, 0x464e3d6d6c352f84),
    ("xorshift-1m-minus-1", 131072, 0x1db1daf2c9ad0169),
    ("zero-1m", 131072, 0x32693adb0e3f9add),
    ("pattern7-1m", 131072, 0x32693adb0e3f9add),
    ("low-entropy-1m", 131072, 0xaa16dedf79d7c399),
    ("alternating-1m", 131072, 0xadde3c7d1be636c9),
    ("odd-eof-transient", 131072, 0x527c042df6f9f7c6),
    ("edge-minimum-1", 131072, 0x04dbd44e15fcaf2b),
    ("edge-minimum+0", 131072, 0xdee25a907715f6e5),
    ("edge-minimum+1", 131072, 0x12631dd93ff987c4),
    ("edge-target-1", 131072, 0x7f07aaf23e217b72),
    ("edge-target+0", 131072, 0x414ce81f3ce2f0d7),
    ("edge-target+1", 131072, 0x2252211631f3a6b6),
    ("edge-maximum-1", 131072, 0x23efad2d3a67c40f),
    ("edge-maximum+0", 131072, 0x6fef63033c4d69fa),
    ("edge-maximum+1", 131072, 0x217e9ab2d20fff1d),
    ("xorshift-1m", 262144, 0x9fb1e2b02eb07bf5),
    ("xorshift-1m-minus-1", 262144, 0x1ac9cf7ca50b8510),
    ("zero-1m", 262144, 0x518662e8401bc7f5),
    ("pattern7-1m", 262144, 0x518662e8401bc7f5),
    ("low-entropy-1m", 262144, 0x760461a5dc0b7709),
    ("alternating-1m", 262144, 0xe9b3b311b10f70f2),
    ("odd-eof-transient", 262144, 0x527c042df6f9f7c6),
    ("edge-minimum-1", 262144, 0x5b9e0f252c1341ab),
    ("edge-minimum+0", 262144, 0xab89bb86730d9e2c),
    ("edge-minimum+1", 262144, 0x45bbbce34401e07d),
    ("edge-target-1", 262144, 0xc5dae28c623def00),
    ("edge-target+0", 262144, 0x15c68eeda9384b81),
    ("edge-target+1", 262144, 0xf6cbc7e49e490160),
    ("edge-maximum-1", 262144, 0x911de9cb6670a0e6),
    ("edge-maximum+0", 262144, 0xf6c86c436bfdaab5),
    ("edge-maximum+1", 262144, 0xe2f2233039eccf80),
];

fn xorshift_bytes(length: usize, seed: u32) -> Vec<u8> {
    let mut state = seed;
    let mut bytes = vec![0u8; length];

    for value in &mut bytes {
        state ^= state << 13;
        state ^= state >> 17;
        state ^= state << 5;
        *value = state as u8;
    }

    bytes
}

// Byte-for-byte the fixtures of fastcdc_reference.py `fixtures`.
fn fixtures(minimum: usize, target: usize, maximum: usize) -> Vec<(String, Vec<u8>)> {
    let random_1m = xorshift_bytes(1024 * 1024, 0x12345678);
    let pattern: Vec<u8> = (0..1024 * 1024).map(|i| random_1m[i % 7]).collect();
    let mut alternating = vec![0u8; 1024 * 1024];
    for block in (0..alternating.len()).step_by(128 * 1024) {
        alternating[block..block + 64 * 1024].copy_from_slice(&random_1m[block..block + 64 * 1024]);
    }
    let mut odd_eof = vec![0u8; 16 * 1024];
    odd_eof.extend_from_slice(&[2, 255, 65]);

    let mut output = vec![
        ("xorshift-1m".to_string(), random_1m.clone()),
        ("xorshift-1m-minus-1".to_string(), random_1m[..random_1m.len() - 1].to_vec()),
        ("zero-1m".to_string(), vec![0u8; 1024 * 1024]),
        ("pattern7-1m".to_string(), pattern),
        ("low-entropy-1m".to_string(), random_1m.iter().map(|b| b & 0x03).collect()),
        ("alternating-1m".to_string(), alternating),
        ("odd-eof-transient".to_string(), odd_eof),
    ];

    let random_edges = xorshift_bytes(maximum + 1, 0x9E3779B9);
    for (name, size) in [("minimum", minimum), ("target", target), ("maximum", maximum)] {
        for delta in [-1i64, 0, 1] {
            let length = (size as i64 + delta) as usize;
            output.push((format!("edge-{name}{delta:+}"), random_edges[..length].to_vec()));
        }
    }

    output
}

fn fnv1a64(cuts: &[(usize, usize)]) -> u64 {
    let mut value: u64 = 0xcbf29ce484222325;
    for &(offset, length) in cuts {
        for byte in (offset as u64).to_le_bytes().into_iter().chain((length as u64).to_le_bytes()) {
            value ^= byte as u64;
            value = value.wrapping_mul(0x100000001b3);
        }
    }
    value
}

fn main() {
    let input = xorshift_bytes(1024 * 1024, 0x12345678);
    let actual: Vec<(usize, usize)> = v2016::FastCDC::new(&input, 16 * 1024, 64 * 1024, 256 * 1024)
        .map(|chunk| (chunk.offset, chunk.length))
        .collect();

    assert_eq!(EXPECTED, actual.as_slice(), "fastcdc-rs v5.0.0 v2016 cut points differ");
    println!("fastcdc-rs 5.0.0 v2016 external vector OK: {} chunks", actual.len());

    // #99 L1: v2016 must reproduce the ChunkShift scalar semantics on every
    // fixture; v2020 (two-byte loop) is compared with v2016 and every
    // difference is reported. Its pairs never test the last position of an
    // odd final window, so v2020 can only differ there.
    let mut checked = 0;
    let mut v2020_differences = Vec::new();

    for &(minimum, target, maximum) in PRESETS {
        for (name, data) in fixtures(minimum, target, maximum) {
            let old: Vec<(usize, usize)> = v2016::FastCDC::new(&data, minimum, target, maximum)
                .map(|chunk| (chunk.offset, chunk.length))
                .collect();
            let new: Vec<(usize, usize)> = v2020::FastCDC::new(&data, minimum, target, maximum)
                .map(|chunk| (chunk.offset, chunk.length))
                .collect();

            let expected = EXPECTED_FIXTURE_DIGESTS
                .iter()
                .find(|(fixture, preset, _)| *fixture == name && *preset == target)
                .unwrap_or_else(|| panic!("no expected digest for {name} at target {target}"))
                .2;
            assert_eq!(expected, fnv1a64(&old), "v2016 differs from ChunkShift on {name} at target {target}");
            checked += 1;

            if old != new {
                assert!(data.len() % 2 == 1, "v2020 differs from v2016 on even-length {name} at target {target}");
                println!("v2020 differs from v2016 on odd-length {name} at target {target}: v2016 tail {:?}, v2020 tail {:?}",
                    &old[old.len().saturating_sub(2)..], &new[new.len().saturating_sub(2)..]);
                v2020_differences.push((name, target));
            }
        }
    }

    assert!(
        v2020_differences.contains(&("odd-eof-transient".to_string(), 64 * 1024)),
        "the odd-EOF fixture no longer separates v2020 from v2016; re-check the two-byte loop"
    );
    println!("fastcdc-rs 5.0.0 v2016 matches ChunkShift on {checked} (fixture, preset) digests; v2020 differs on {} odd final windows", v2020_differences.len());
}
