<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <IsAotCompatible>true</IsAotCompatible>
    <EnablePackageValidation>true</EnablePackageValidation>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ChunkShift.Tests" />
  </ItemGroup>

</Project>